### ISSUE TITLE
Receive Error while Restart

### ISSUE THREAD

**Issue by robrec** [kakaki/homebridge-mqtt-thermostats#1]
Hey,

Thank you for your work!

Unfortunately i receive some errors with this code(95% its my mistake but i didnt find any solution that works) so here is my code:

    "platforms": [
        {
            "name": "Config",
            "port": 8000,
            "auth": "form",
            "theme": "green",
            "sudo": true,
            "platform": "config"
        },
    
	{
            "platform": "mqttThermostats",
            "name": "mqttThermostats",
            "url": "mqtt://localhost",
    		"username": "xxx",
            "password": "xxx",
            "heat_name": "Heizung",
            "heat_topic_get": "stat/heizung/schlafzimmer/status",
            "heat_topic_set": "stat/heizung/schlafzimmer/status/set",
            "heat_on_value": "ON",
            "heat_off_value": "OFF",
            "thermostats": [
                {
                    "name": "Schlafzimmer",
                    "topics" :
                        {
                        "getCurrentTemperature": "stat/heizung/schlafzimmer/target_temperature",
                        "setOn": "stat/heizung/schlafzimmer/target_temperature/set"
                        }
                }
           ]
        }
],
 "accessories": [
        {...}
]

any ideas?

**Comment by kakaki** [comment]
What error is showing in console ?

**Comment by EugeneSok** [comment]
Hey. I have Error too when trying loading Homebridge. That have message about the platform can't get permission

**Comment by EugeneSok** [comment]
Any ideas?

**Comment by kakaki** [comment]
A need error from console, it should show some info

**Comment by EugeneSok** [comment]
Load homebridge-mqtt-thermostats.mqttThermostats

/usr/local/lib/node_modules/homebridge-mqtt-thermostats/index.js:29
                this.thermostats = config.thermostats || {};
                            ^
TypeError: Cannot read property 'thermostats' of null
    at new mqttThermostatsPlatform (/usr/local/lib/node_modules/homebridge-mqtt-thermostats/index.js:29:29)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:347:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:88:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)

**Comment by EugeneSok** [comment]
What i need to do?

**Comment by kakaki** [comment]
> What i need to do?
From error it looks like config is not set.
